# Generated by Django 2.2.1 on 2020-08-29 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_aproblem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aproblem',
        ),
    ]
