# Generated by Django 2.2.1 on 2020-09-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_aproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='p_sort',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
