# Generated by Django 2.2.4 on 2020-09-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200911_1626'),
        ('user', '0004_problem_p_sort'),
    ]

    operations = [
    ]
