# Generated by Django 2.2.4 on 2020-10-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200925_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dino_level',
            field=models.IntegerField(default=0),
        ),
    ]
