# Generated by Django 2.2.4 on 2020-10-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_correct_wrong'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exp',
            field=models.IntegerField(default=1),
        ),
    ]
