# Generated by Django 2.2.4 on 2020-10-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_student_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
