# Generated by Django 2.2.4 on 2020-10-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_student_dino_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='p_title',
            new_name='p_era',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='p_sort',
        ),
    ]
