# Generated by Django 2.2.4 on 2020-10-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20201018_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='chs_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='gh_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='sg_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='ss_num',
            field=models.IntegerField(default=0),
        ),
    ]
