# Generated by Django 2.2.4 on 2020-09-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heritage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('dynasty', models.CharField(max_length=255)),
                ('img_url', models.TextField()),
                ('content', models.TextField()),
                ('longitude', models.TextField()),
                ('latitude', models.TextField()),
            ],
        ),
    ]
